chore: change tsconfig module resolution to Node
Changes the `moduleResolution` to `Node` because during the tsup build, the TypeScript error "error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'." occurs.